package dev.test

/**
 * Loads a [Class] object from [ByteArray] of byte-code.
 */
class InjectedClassLoader : ClassLoader() {

    /**
     * Creates a [Class] object from a sub-type of [name] and
     * the generated bytecode from [bytes]
     */
    fun injectClass(name: String, bytes: ByteArray): Class<*> {
        return defineClass(name, bytes, 0, bytes.size)
    }

}